-- MySQL Script generated by MySQL Workbench
-- Fri Dec 15 07:42:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema University
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema University
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `University` DEFAULT CHARACTER SET utf8 ;
USE `University` ;

-- -----------------------------------------------------
-- Table `University`.`DEPARTMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`DEPARTMENT` (
  `Department_ID` BIGINT(5) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `LOCATION` VARCHAR(45) NULL,
  PRIMARY KEY (`Department_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`SCHEDULE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`SCHEDULE` (
  `SCHEDULE_ID` BIGINT(5) NOT NULL,
  `COURSE_ID` BIGINT(5) NOT NULL,
  `ROOM_ID` BIGINT(5) NOT NULL,
  `DAY_OF_WEEK` TINYINT(5) NULL,
  `START_TIME` TIMESTAMP(5) NULL,
  `END_TIME` TIMESTAMP(5) NULL,
  PRIMARY KEY (`SCHEDULE_ID`, `COURSE_ID`, `ROOM_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`COURSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`COURSE` (
  `COURSE_ID` BIGINT NOT NULL,
  `DEPARTMENT_ID` BIGINT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `CREDITS` TINYINT(5) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  PRIMARY KEY (`COURSE_ID`, `DEPARTMENT_ID`),
  INDEX `fk_COURSE_DEPARTMENT_idx` (`DEPARTMENT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_COURSE_DEPARTMENT`
    FOREIGN KEY (`DEPARTMENT_ID`)
    REFERENCES `University`.`DEPARTMENT` (`Department_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COURSE_SCHEDULE1`
    FOREIGN KEY (`COURSE_ID`)
    REFERENCES `University`.`SCHEDULE` (`COURSE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`INSTRUCTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`INSTRUCTOR` (
  `EMAIL` VARCHAR(45) NULL,
  `INSTRUCTOR_ID` BIGINT(5) NOT NULL,
  `DEPARTMENT_ID` BIGINT(5) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `HIRE_DATE` TIMESTAMP(5) NULL,
  PRIMARY KEY (`INSTRUCTOR_ID`, `DEPARTMENT_ID`),
  INDEX `fk_INSTRUCTOR_DEPARTMENT1_idx` (`DEPARTMENT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_INSTRUCTOR_DEPARTMENT1`
    FOREIGN KEY (`DEPARTMENT_ID`)
    REFERENCES `University`.`DEPARTMENT` (`Department_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`STUDENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`STUDENT` (
  `STUDENT_ID` BIGINT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NULL,
  `ENROLLMENT_DATE` TIMESTAMP(5) NULL,
  PRIMARY KEY (`STUDENT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`ROOM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`ROOM` (
  ` ROOM_ID` BIGINT(5) NOT NULL,
  `BUILDING_NAME` VARCHAR(45) NULL,
  ` ROOM_NUMBER` VARCHAR(45) NULL,
  `CAPACITY` TINYINT(5) NULL,
  PRIMARY KEY (` ROOM_ID`),
  CONSTRAINT `fk_ROOM_SCHEDULE1`
    FOREIGN KEY (` ROOM_ID`)
    REFERENCES `University`.`SCHEDULE` (`ROOM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`ENROLLMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`ENROLLMENT` (
  `ENROLLMENT_ID` BIGINT NOT NULL,
  `STUDENT_ID` BIGINT NOT NULL,
  `COURSE_ID` BIGINT NOT NULL,
  `ENROLLMENT_DATE` TIMESTAMP NULL,
  PRIMARY KEY (`ENROLLMENT_ID`, `COURSE_ID`),
  INDEX `fk_ENROLLMENT_has_COURSE_COURSE1_idx` (`COURSE_ID` ASC, `ENROLLMENT_DATE` ASC) VISIBLE,
  INDEX `fk_ENROLLMENT_STUDENT1_idx` (`STUDENT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ENROLLMENT_has_COURSE_COURSE1`
    FOREIGN KEY (`COURSE_ID` , `ENROLLMENT_DATE`)
    REFERENCES `University`.`COURSE` (`COURSE_ID` , `DEPARTMENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ENROLLMENT_STUDENT1`
    FOREIGN KEY (`STUDENT_ID`)
    REFERENCES `University`.`STUDENT` (`STUDENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`GRADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`GRADE` (
  `GRADE_ID` BIGINT(5) NOT NULL,
  ` ENROLLMENT_ID` BIGINT(5) NOT NULL,
  `ASSIGNMENT_ID` BIGINT(5) NOT NULL,
  `SCORE` DOUBLE NULL,
  PRIMARY KEY (`GRADE_ID`, ` ENROLLMENT_ID`, `ASSIGNMENT_ID`),
  INDEX `fk_GRADE_ENROLLMENT1_idx` (` ENROLLMENT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_GRADE_ENROLLMENT1`
    FOREIGN KEY (` ENROLLMENT_ID`)
    REFERENCES `University`.`ENROLLMENT` (`ENROLLMENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`ASSIGNMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`ASSIGNMENT` (
  `ASSIGNMENT_ID` BIGINT(5) NOT NULL,
  `COURSE_ID` BIGINT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `DUE_DATE` TIMESTAMP(5) NULL,
  PRIMARY KEY (`ASSIGNMENT_ID`),
  INDEX `fk_ASSIGNMENT_COURSE1_idx` (`COURSE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ASSIGNMENT_COURSE1`
    FOREIGN KEY (`COURSE_ID`)
    REFERENCES `University`.`COURSE` (`COURSE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ASSIGNMENT_GRADE1`
    FOREIGN KEY (`ASSIGNMENT_ID`)
    REFERENCES `University`.`GRADE` (`ASSIGNMENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`PREREQUISITE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`PREREQUISITE` (
  `PREREQUISITE_ID` BIGINT NOT NULL,
  `COURSE_ID` BIGINT NOT NULL,
  `PREREQUISITE_COURSE_ID` BIGINT NOT NULL,
  PRIMARY KEY (`PREREQUISITE_ID`),
  INDEX `fk_PREREQUISITE_COURSE1_idx` (`COURSE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PREREQUISITE_COURSE1`
    FOREIGN KEY (`COURSE_ID`)
    REFERENCES `University`.`COURSE` (`COURSE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`RESEARCH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`RESEARCH` (
  `RESEARCH_ID` BIGINT(5) NOT NULL,
  ` FACULTY_ID` BIGINT(5) NOT NULL,
  `TITLE` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  ` START_DATE` TIMESTAMP NULL,
  `END_DATE` TIMESTAMP NULL,
  PRIMARY KEY (`RESEARCH_ID`, ` FACULTY_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`FACULTY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`FACULTY` (
  `FACULTY_ID` BIGINT(5) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `DEPARTMENT_ID` BIGINT(5) NOT NULL,
  `POSITION` VARCHAR(45) NULL,
  PRIMARY KEY (`FACULTY_ID`, `DEPARTMENT_ID`),
  INDEX `fk_FACULTY_DEPARTMENT1_idx` (`DEPARTMENT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_FACULTY_DEPARTMENT1`
    FOREIGN KEY (`DEPARTMENT_ID`)
    REFERENCES `University`.`DEPARTMENT` (`Department_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACULTY_RESEARCH1`
    FOREIGN KEY (`FACULTY_ID`)
    REFERENCES `University`.`RESEARCH` (` FACULTY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
